name = "talkto"
compatibility_date = "2024-02-09"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
name = "talkto"
route = "talkto.pages.dev/*"

[build.upload]
format = "service-worker"