name = "talkto"
compatibility_date = "2024-02-09"
main = ".next/server/app/api/chat/route.js"

[build]
command = "npm run build"
output_directory = ".next"

[site]
bucket = ".next"

[env.production]
name = "talkto"
route = "talkto.pages.dev/*"

[build.upload]
format = "service-worker"