name = "talkto"
compatibility_date = "2024-02-09"
compatibility_flags = ["nodejs_compat"]

main = "src/worker.ts"

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = ".next"

[env.production]
name = "talkto"
route = "talkto.pages.dev/*"